Ticket 101 - this is my first pull request
twhentea/classrepo pull request #1
Opened 2023-06-19 23:22 UTC by olatunjifagade

i made 2 changes to the last two lines

2023-06-19 23:28 UTC, twhentea commented
test seen

2023-06-19 23:34 UTC, twhentea requested changes
This is rubbish

2023-06-19 23:48 UTC, twhentea approved these changes

2023-06-19 23:55 UTC, twhentea approved these changes

2023-06-21 16:26 UTC, closed without merging

2023-06-21 16:26 UTC, olatunjifagade commented
made the changes to solve the conflict